version: "3.9"

services:
  sphinx-blog-build:
    build:
      context: .
    image: jacobsapps/sphinx-blog
    container_name: sphinx-blog-build
    volumes:
      - ./content:/usr/src/app/source/content
      - ./build:/usr/src/app/build
    command: sphinx-build -a source build
  sphinx-blog-run:
    build:
      context: .
    image: jacobsapps/sphinx-blog
    container_name: sphinx-blog-run
    ports:
      - 8888:8888
    volumes:
      - ./content:/usr/src/app/source/content
      - ./build:/usr/src/app/build
    command: sphinx-autobuild -E source build --host 0.0.0.0 --port 8888