``` {uml}

    @startuml

    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

    title Container Diagram

    Person(person, "User")

    System_Boundary(system, "Order System") {
        Container(api, "Order Api", ".NET 5 Api", "Queues incoming orders for processing")
        Container(queue, "Queue", "RabbitMq", "Queue for infoming order events")
        Container(worker, "Worker", ".NET 5 Worker", "Processes orders, stores orders in database")
        ContainerDb(database, "Database", "PostgreSQL", "Stores processed orders")
    }

    person <-down-> api: Sends unprocessed orders\nRequests processed orders
    api -down-> queue: Unprocessed orders
    queue -down-> worker: Subscription on new order events 
    worker -> database: Processed orders
    database -up-> api: Processed orders

    @enduml

```