name: Generate Blog
on: push
jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Build HTML
        run: ./docker-build.sh
      #    - uses: seanzhengw/sphinx-pages@master
      #with:
      #  github_token: ${{ secrets.GITHUB_TOKEN }}
      #  create_readme: true
      #  source_dir: ./source
