name: Generate Blog
on: push
jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - name: Install plantuml
      run: sudo apt-get install -y plantuml
    - name: get plantuml location
      run: which plantuml
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        source_dir: ./source
